
CREATE TABLE COMPANY
(
  COMPANY_NAME VARCHAR(50) NOT NULL COMMENT '업체명',
  PHONE_NUMBER VARCHAR(50) NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(50) NOT NULL COMMENT '주소',
  ROAD_ADDRESS VARCHAR(50) NOT NULL COMMENT '도로명주소'
) COMMENT '업체정보';
