
CREATE TABLE MEMBER_INFORMATION
(
  MEMBER_INFORMATION_ID VARCHAR(50) NULL     COMMENT 'PK',
  NAME                  VARCHAR(50) NULL     COMMENT '이름',
  USERNAME              VARCHAR(50) NULL     COMMENT '회원ID(FK)',
  PASSWORD              VARCHAR(50) NULL     COMMENT '비밀번호',
  BIRTHDATE             VARCHAR(50) NULL     COMMENT '생년월일',
  GENDER                VARCHAR(50) NULL     COMMENT '성별',
  PHONE_NUMBER          VARCHAR(50) NULL     COMMENT '폰번호',
  EMAIL_ADDRESS         VARCHAR(50) NULL     COMMENT '이메일주소',
  ADDRESS               VARCHAR(50) NULL     COMMENT '주소 '
) COMMENT '회원정보 ';

CREATE TABLE MEMBERS_LOGIN
(
  MEMBERS_LOGIN_ID VARCHAR(50) NULL     COMMENT 'PK',
  USERNAME         VARCHAR(50) NULL     COMMENT '회원ID(FK)',
  PASSWORD         VARCHAR(50) NULL     COMMENT '비밀번호'
) COMMENT '회원로그인';
