
CREATE TABLE MEMBER_INFORMATION
(
  MEMBER_INFORMATION_ID VARCHAR(50) NOT NULL COMMENT 'PK',
  NAME                  VARCHAR(50) NULL     COMMENT '이름',
  USERNAME              VARCHAR(50) NULL     COMMENT '회원ID',
  PASSWORD              VARCHAR(50) NULL     COMMENT '비밀번호',
  BIRTHDATE             VARCHAR(50) NULL     COMMENT '생년월일',
  GENDER                VARCHAR(50) NULL     COMMENT '성별',
  PHONE_NUMBER          VARCHAR(50) NULL     COMMENT '폰번호',
  EMAIL_ADDRESS         VARCHAR(50) NULL     COMMENT '이메일주소',
  ADDRESS               VARCHAR(50) NULL     COMMENT '주소',
  PRIMARY KEY (MEMBER_INFORMATION_ID)
) COMMENT '회원정보';

CREATE TABLE RESERVATION HISTORY
(
  MEMBER_INFORMATION_ID  VARCHAR(50) NOT NULL COMMENT 'FK',
  RESERVATION HISTORY_ID VARCHAR(50) NOT NULL COMMENT 'PK',
  RESERVATION_DATE       VARCHAR(50) NULL     COMMENT '예약날짜',
  RESERVATION_TIME       VARCHAR(50) NULL     COMMENT '예약시간',
  NOTES                  VARCHAR(50) NULL     COMMENT '참고사항',
  CENTER_NAME            VARCHAR(50) NULL     COMMENT '센터명',
  PRIMARY KEY (RESERVATION HISTORY_ID)
) COMMENT '예약내역';

ALTER TABLE RESERVATION HISTORY
  ADD CONSTRAINT FK_MEMBER_INFORMATION_TO_RESERVATION HISTORY
    FOREIGN KEY (MEMBER_INFORMATION_ID)
    REFERENCES MEMBER_INFORMATION (MEMBER_INFORMATION_ID);


CREATE TABLE BOARD
(
  NUMBER   INTEGER     NOT NULL COMMENT '번호',
  ID       VARCHAR(50) NOT NULL COMMENT '아이디',
  TITLE    VARCHAR(50) NOT NULL COMMENT '제목',
  CONTENTS VARCHAR(50) NOT NULL COMMENT '내용',
  DATE     VARCHAR(50) NOT NULL COMMENT '날짜',
  VIEWS    INTEGER     NOT NULL COMMENT '조회수'
) COMMENT '게시판 리스트';


CREATE TABLE COMPANY
(
  COMPANY_NAME VARCHAR(50) NOT NULL COMMENT '업체명',
  PHONE_NUMBER VARCHAR(50) NOT NULL COMMENT '전화번호',
  ADDRESS      VARCHAR(50) NOT NULL COMMENT '주소',
  ROAD_ADDRESS VARCHAR(50) NOT NULL COMMENT '도로명주소'
) COMMENT '업체정보';


CREATE TABLE MEMBER_INFORMATION
(
  MEMBER_INFORMATION_ID VARCHAR(50) NULL     COMMENT 'PK',
  NAME                  VARCHAR(50) NULL     COMMENT '이름',
  USERNAME              VARCHAR(50) NULL     COMMENT '회원ID(FK)',
  PASSWORD              VARCHAR(50) NULL     COMMENT '비밀번호',
  BIRTHDATE             VARCHAR(50) NULL     COMMENT '생년월일',
  GENDER                VARCHAR(50) NULL     COMMENT '성별',
  PHONE_NUMBER          VARCHAR(50) NULL     COMMENT '폰번호',
  EMAIL_ADDRESS         VARCHAR(50) NULL     COMMENT '이메일주소',
  ADDRESS               VARCHAR(50) NULL     COMMENT '주소 '
) COMMENT '회원정보 ';

CREATE TABLE MEMBERS_LOGIN
(
  MEMBERS_LOGIN_ID VARCHAR(50) NULL     COMMENT 'PK',
  USERNAME         VARCHAR(50) NULL     COMMENT '회원ID(FK)',
  PASSWORD         VARCHAR(50) NULL     COMMENT '비밀번호'
) COMMENT '회원로그인';


CREATE TABLE NOTICE
(
  NOTICE_ID    VARCHAR(50) NOT NULL COMMENT '공지사항ID(PK)',
  NOTICE_TITLE VARCHAR(50) NULL     COMMENT '공지제목',
  USERNAME     VARCHAR(50) NULL     COMMENT '공지작성자(FK)',
  NOTICE_DATE  VARCHAR(50) NULL     COMMENT '공지날짜',
  NOTICE_VIEWS VARCHAR(50) NULL     COMMENT '공지조회',
  PRIMARY KEY (NOTICE_ID)
) COMMENT '공지사항';


CREATE TABLE RESEVATION_HISTORY
(
  USER_ID         VARCHAR(50) NOT NULL COMMENT '예약ID',
  RESEVATION_DATE VARCHAR(50) NOT NULL COMMENT '예약날짜',
  RESEVATION_TIME VARCHAR(50) NOT NULL COMMENT '예약시간',
  NOTES           VARCHAR(50) NOT NULL COMMENT '참고사항',
  CENTER_NAME     VARCHAR(50) NOT NULL COMMENT '센터명'
) COMMENT '예약내역';


CREATE TABLE REVIEW
(
  ID           VARCHAR(50) NOT NULL COMMENT '아이디',
  COMPANY_NAME VARCHAR(50) NOT NULL COMMENT '업체명',
  REVIEW       VARCHAR(50) NOT NULL COMMENT '리뷰',
  GRADE        VARCHAR(50) NOT NULL COMMENT '평점'
) COMMENT '후기';


CREATE TABLE AUTH_NAMES
(
  AUTH_NAME VARCHAR(200) NOT NULL COMMENT '접근권한명',
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '접근권한 대표값',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '접근권한명';

CREATE TABLE AUTHS
(
  UNIQUE_ID_USERS      VARCHAR(200) NOT NULL COMMENT '대표값',
  UNIQUE_ID_AUTH_NAMES VARCHAR(200) NOT NULL COMMENT '접근권한 대표값',
  PRIMARY KEY (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
) COMMENT '권한들';

CREATE TABLE USERS
(
  UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '대표값',
  NAME      VARCHAR(200) NOT NULL COMMENT '이름',
  EMAIL     VARCHAR(200) NOT NULL COMMENT '이메일',
  JOB       VARCHAR(200) NULL     COMMENT '직책',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '사용자들';

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_USERS_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_USERS)
    REFERENCES USERS (UNIQUE_ID);

ALTER TABLE AUTHS
  ADD CONSTRAINT FK_AUTH_NAMES_TO_AUTHS
    FOREIGN KEY (UNIQUE_ID_AUTH_NAMES)
    REFERENCES AUTH_NAMES (UNIQUE_ID);

