
CREATE TABLE NOTICE
(
  NOTICE_ID    VARCHAR(50) NOT NULL COMMENT '공지사항ID(PK)',
  NOTICE_TITLE VARCHAR(50) NULL     COMMENT '공지제목',
  USERNAME     VARCHAR(50) NULL     COMMENT '공지작성자(FK)',
  NOTICE_DATE  VARCHAR(50) NULL     COMMENT '공지날짜',
  NOTICE_VIEWS VARCHAR(50) NULL     COMMENT '공지조회',
  PRIMARY KEY (NOTICE_ID)
) COMMENT '공지사항';
