
CREATE TABLE RESEVATION_HISTORY
(
  USER_ID         VARCHAR(50) NOT NULL COMMENT '예약ID',
  RESEVATION_DATE VARCHAR(50) NOT NULL COMMENT '예약날짜',
  RESEVATION_TIME VARCHAR(50) NOT NULL COMMENT '예약시간',
  NOTES           VARCHAR(50) NOT NULL COMMENT '참고사항',
  CENTER_NAME     VARCHAR(50) NOT NULL COMMENT '센터명'
) COMMENT '예약내역';
