
CREATE TABLE REVIEW
(
  ID           VARCHAR(50) NOT NULL COMMENT '아이디',
  COMPANY_NAME VARCHAR(50) NOT NULL COMMENT '업체명',
  REVIEW       VARCHAR(50) NOT NULL COMMENT '리뷰',
  GRADE        VARCHAR(50) NOT NULL COMMENT '평점'
) COMMENT '후기';
